# Generated by Django 3.2.4 on 2021-06-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210612_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='doubles_points',
            new_name='double_points',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='doubles_ranking',
            new_name='double_ranking',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='singles_ranking',
            new_name='single_ranking',
        ),
    ]
