# Generated by Django 3.2.4 on 2021-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210612_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='double_points',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='single_points',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
    ]
