# Generated by Django 3.2.4 on 2021-06-10 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorekeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_a', models.IntegerField(blank=True, null=True)),
                ('points_b', models.IntegerField(blank=True, null=True)),
                ('outcome_a', models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], max_length=2)),
                ('outcome_b', models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], max_length=2)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_player', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_player', to=settings.AUTH_USER_MODEL)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['match_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
