# Generated by Django 3.2.4 on 2021-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeeper', '0002_auto_20210611_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_a_increment',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player_b_increment',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
