# Generated by Django 3.2.4 on 2021-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeeper', '0003_auto_20210612_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_a_increment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_b_increment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
